export const GET_DESSERTS = "GET_DESSERTS";
export const DESSERTSS_LOADING = "DESSERTSS_LOADING";
export const ADD_DESSERT_TO_CART = "ADD_DESSERT_TO_CART";
export const REMOVE_DESSERT_FROM_CART = "REMOVE_DESSERT_FROM_CART";
export const ADJUST_DESSERT_QTY = "ADJUST_DESSERT_QTY";
export const REMOVE_ALL_DESSERTS = "REMOVE_ALL_DESSERTS";
