export const GET_DRINKS = "GET_DRINKS";
export const DRINKS_LOADING = "DRINKS_LOADING";
export const ADD_DRINK_TO_CART = "ADD_DRINK_TO_CART";
export const REMOVE_DRINK_FROM_CART = "REMOVE_DRINK_FROM_CART";
export const ADJUST_DRINK_QTY = "ADJUST_DRINK_QTY";
export const REMOVE_ALL_DRINKS = "REMOVE_ALL_DRINKS";
